version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - db
      - node

  node:
    build:
      context: node
    container_name: node
    networks:
      - node-network
    depends_on: 
      - db
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    tty: true
    restart: always
    networks:
      - node-network
    volumes:
      # - nodemysqldb:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root


networks:
  node-network:
    driver: bridge

# volumes:
#   nodemysqldb: